### ISSUE TITLE
not enough material for data entity?

### ISSUE THREAD

**Issue by kiasyn** [kiasyn/SamTrain#30]

**Comment by EugeneKay** [comment]
I am experiencing this, but it's totally work-around-able once I understood what was going on.

Blueprints of Depot/Supply/Consumer train stops include the "Train Stop Data" entity, which is not available in inventory / craftable / placeable by bots.  However, when a bot places the train stop it does place a new hidden data entity, which starts with blank train stop settings. Presumably, if the blueprinted entity were to become placed, it would "just work". An additional wrinkle is that the Infinity Mode mod's setting for 'Instant Blueprint' does NOT auto-place this new data entity, NOR does it place the blueprinted data - so the train stop doesn't work as designed at all.

What I have done is exclude the hidden data entity from my blueprints, by right-clicking it from the entity list when creating a blueprint. This is not possible with Ctrl-C / Ctrl-V, so I just don't use those shortcuts. 

I think that if you set not-blueprintable on the hidden data entity it would deal with "not enough material" by ensuring they are never blueprinted. Willing to test ;-)

**Comment by kiasyn** [comment]
Hey,

So the train stop data entity has to be blueprintable, as it stores a json encoded serialization of the data on the stop (resource, priority, etc).

This is so when the blueprint is placed the stop gets all the data copied to it.

I may just have to look for the blueprint ghost and then instantly make it built, or something. I'm not sure how to fix it yet.

**Comment by EugeneKay** [comment]
Correct - the "hidden data entity" needs to be placed in order for that serialized data to be created. But since there is no way to craft the hidden data entity, it is difficult to get one into the inventory. I found out that you can do this by placing a bunch of Depot/Supplier/Consumer stations, then use the Deconstruction Planner to get them into inventory (via bots). Right-click deconstruction (mining) does not yield a "hidden data entity" object.

Further, it is possible to use Logistic Request Slots (again, I am using Infinity Mode) to get a full stack of these data-entity objects, and THEN blueprints seem to work correctly.

**Comment by kiasyn** [comment]
if you are using cheats you can use this command to add data entities to your inventory:

/c game.player.insert{name="st-data-entity"}

Your workaround will also work.

Ideally deconstruction planner should destroy the entities without getting them into inventory, but it would probably be a bad idea to fix that before fixing the hidden data entity being required to be placed by bots.
